services:
  db:
    image: postgres:15.5
    environment:
      POSTGRES_DB: app_development
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  back:
    build:
      context: ${BACK_DIR:-./back}
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ${BACK_DIR:-./back}:/app
    ports:
      - "3100:3000"
    depends_on:
      db:
        condition: service_started
    tty: true
    stdin_open: true
    env_file:
      - ${BACK_DIR:-./back}/.env
    environment:
      - RAILS_ENV=development
      - PGPASSWORD=password
      - BUNDLE_PATH=/app/vendor/bundle
      - JWT_SECRET=ZATdfgMg5Udn7Ozm1qSKQM6qWzDb2wZt2ZqJoXXS08w=
      - CONFIRM_SUCCESS_URL=http://localhost:8100/signin
      - FRONTEND_URL=http://localhost:8100
  front:
    build:
      context: ${FRONT_DIR:-./front}
      dockerfile: Dockerfile
    volumes:
      - ${FRONT_DIR:-./front}:/app
      - /app/node_modules
    command: sh -c "rm -rf /app/.next && yarn install && yarn dev -p 4100"
    ports:
      - "8100:4100"
volumes:
  postgres_data:
